steps:
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - -t
  - asia-northeast1-docker.pkg.dev/$PROJECT_ID/${_SERVICE}/${_SERVICE}:latest
  - -f
  - Dockerfile
  - .

- name: gcr.io/cloud-builders/docker
  args:
  - push
  - asia-northeast1-docker.pkg.dev/$PROJECT_ID/${_SERVICE}/${_SERVICE}:latest

- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
  - run
  - deploy
  - ${_SERVICE}
  - --image
  - asia-northeast1-docker.pkg.dev/$PROJECT_ID/${_SERVICE}/${_SERVICE}:latest
  - --region
  - ${_REGION}
  - --platform
  - managed
  - --allow-unauthenticated
  - --add-cloudsql-instances
  - ${_CLOUDSQL_INSTANCE}
  - --set-env-vars
  - GOOGLE_CLOUD_PROJECT=$PROJECT_ID,API_URL=https://api.taucho.org,API_AUDIENCE=${_API_AUDIENCE}
  - --set-secrets
  - DATABASE_URL=DATABASE_URL:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,GOOGLE_REDIRECT_URL=GOOGLE_REDIRECT_URL:latest

substitutions:
  _SERVICE: tauchoportal
  _REGION: asia-northeast1
  _CLOUDSQL_INSTANCE: tauchopostgres-prod:asia-northeast1:tauchodb
  _API_AUDIENCE: https://tauchoapis-w7tb2uu4fq-an.a.run.app
