steps:
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - -t
  - us-west2-docker.pkg.dev/$PROJECT_ID/${_SERVICE}/${_SERVICE}:latest
  - -f
  - Dockerfile
  - .

- name: gcr.io/cloud-builders/docker
  args:
  - push
  - us-west2-docker.pkg.dev/$PROJECT_ID/${_SERVICE}/${_SERVICE}:latest

- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
  - run
  - deploy
  - ${_SERVICE}
  - --image
  - us-west2-docker.pkg.dev/$PROJECT_ID/${_SERVICE}/${_SERVICE}:latest
  - --region
  - ${_REGION}
  - --platform
  - managed
  - --allow-unauthenticated
  - --add-cloudsql-instances
  - ${_CLOUDSQL_INSTANCE}
  - --set-env-vars
  - GOOGLE_CLOUD_PROJECT=$PROJECT_ID
  - --set-secrets
  - DATABASE_URL=DATABASE_URL:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,GOOGLE_REDIRECT_URL=GOOGLE_REDIRECT_URL:latest

substitutions:
  _SERVICE: tauchoportal
  _REGION: us-west2
  _CLOUDSQL_INSTANCE: tauchopostgres:us-west2:tauchodb
